"""Focused tests for change-description and justification field separation."""

from __future__ import annotations

from datetime import UTC, datetime

from backend.app.services.formatting.servicenow_formatter import SERVICE_NOW_FIELD_NAMES
from backend.app.services.validation.output_repair import repair_change_intent_fields
from backend.app.services.validation.output_validator import (
    validate_change_intent_field_separation,
)
from backend.app.services.validation.service import validate_and_assemble_outputs

FUNCTIONAL_DESCRIPTION = (
    "This change updates the ASAC contact-center production application to improve automated "
    "account-closure processing and support ongoing ASAC functionality. It corrects task "
    "sequencing so dependent actions occur only after the Close Account task is completed. It "
    "improves creation and assignment of manual and automated follow-up tasks and resolves defects "
    "affecting account-condition prompts, task visibility, timestamps, team assignments, and action "
    "controls. Supporting production changes stabilize Dynamics and Guardian integration "
    "interactions used by the ASAC solution and preserve event-processing pipeline behavior. "
    "Together, these enhancements deliver more consistent account-closure processing, clearer task "
    "state, and dependable handoffs across automated and manual activities used by member-service "
    "and operations teams."
)

DISTINCT_JUSTIFICATION = (
    "This change is necessary to improve the correctness and reliability of production "
    "account-closure processing. Existing behavior can execute dependent actions out of sequence, "
    "suppress required member-service prompts, and leave follow-up tasks or controls incomplete or "
    "inconsistent. Addressing these defects reduces the risk of incomplete account handling, "
    "improves operational consistency and task-assignment accuracy, and makes the affected "
    "application and integrations more supportable. Without the change, supported account-closure "
    "scenarios may continue to require avoidable manual investigation or correction."
)


def _full_llm_output(change_description: str, justification: str) -> dict[str, object]:
    return {
        "schema_version": "1.0",
        "build_id": 101,
        "generated_at": datetime.now(UTC).isoformat(),
        "model_metadata": {
            "provider": "azure_openai",
            "deployment": "test-deployment",
            "api_version": "2024-10-21",
            "auth_mode": "entra",
            "prompt_versions": {"bucket_1": "1.2", "bucket_2": "1.1", "bucket_3": "1.1"},
        },
        "bucket_1": {
            "change_description": change_description,
            "short_change_description": "Update ASAC account-closure processing",
            "justification": justification,
            "evidence_used": ["work_item:1001"],
            "model_confidence": 0.85,
        },
        "bucket_2": {
            "testing_performed": "Available lower-environment validation evidence was reviewed.",
            "implementation_plan": "Deploy through the approved release process.",
            "validation_plan": "Validate application health and account-closure behavior.",
            "evidence_used": ["pipeline_task:validation"],
            "model_confidence": 0.75,
        },
        "bucket_3": {
            "backout_plan": "Restore the previous known-good application version if needed.",
            "risk_impact_analysis": "Account-processing behavior requires post-change review.",
            "evidence_used": ["work_item:1001"],
            "model_confidence": 0.7,
        },
    }


def _evidence_bundle() -> dict[str, object]:
    return {
        "bucket_1": {
            "work_item_evidence": [{"id": 1001}],
            "commit_evidence": [{"id": "abc123"}],
            "pull_request_evidence": [],
        },
        "bucket_2": {
            "test_evidence": {"total_tests": 0, "missing_test_context": ["not_collected"]},
        },
        "bucket_3": {
            "artifact_evidence": [{"name": "release-output"}],
            "rollback_indicators": [],
        },
        "source_ref_map": {
            "work_item:1001": {"original_ref": "canonical.change_context.work_items[0]"}
        },
    }


def test_repair_removes_delivery_metadata_and_retains_functional_change() -> None:
    delivery_details = (
        " Build 12345 from the feature/asac branch is deployed through the ASAC-Release "
        "pipeline. The release package artifact app-release.zip was generated by pipeline from "
        "source commit abc123 using CI/CD automation."
    )

    repaired, notes = repair_change_intent_fields(
        {
            "change_description": FUNCTIONAL_DESCRIPTION + delivery_details,
            "justification": DISTINCT_JUSTIFICATION,
        }
    )

    description = str(repaired["change_description"])
    for prohibited_value in (
        "12345",
        "ASAC-Release",
        "feature/asac",
        "app-release.zip",
        "abc123",
        "CI/CD",
        "generated by pipeline",
    ):
        assert prohibited_value not in description
    for retained_value in (
        "ASAC contact-center production application",
        "automated account-closure processing",
        "corrects task sequencing",
        "task visibility",
        "event-processing pipeline behavior",
        "more consistent account-closure processing",
    ):
        assert retained_value in description
    assert notes == ["Removed delivery metadata from change_description."]


def test_repair_removes_delivery_metadata_from_justification() -> None:
    justification = (
        DISTINCT_JUSTIFICATION
        + " Build ID 991 was generated by pipeline and deployed through the release pipeline."
    )

    repaired, notes = repair_change_intent_fields(
        {"change_description": FUNCTIONAL_DESCRIPTION, "justification": justification}
    )

    assert repaired["justification"] == DISTINCT_JUSTIFICATION
    assert "Removed delivery metadata from justification." in notes


def test_repair_condenses_repeated_description_when_supported_rationale_remains() -> None:
    repeated_context = (
        "This change updates the ASAC contact-center production application to improve automated "
        "account-closure processing."
    )
    justification = (
        repeated_context
        + " It is necessary because inconsistent task sequencing creates an operational risk; "
        "the correction improves reliability and supportability."
    )

    repaired, notes = repair_change_intent_fields(
        {"change_description": repeated_context, "justification": justification}
    )

    assert repaired["justification"] == (
        "It is necessary because inconsistent task sequencing creates an operational risk; "
        "the correction improves reliability and supportability."
    )
    assert "Removed description-like sentences from justification." in notes


def test_similarity_validation_flags_substantially_copied_justification() -> None:
    issues = validate_change_intent_field_separation(
        {
            "change_description": FUNCTIONAL_DESCRIPTION,
            "justification": FUNCTIONAL_DESCRIPTION,
        }
    )

    codes = {issue.code for issue in issues}
    assert "JUSTIFICATION_REPETITIVE" in codes
    assert "FIELD_PURPOSE_OVERLAP" in codes


def test_similarity_validation_accepts_distinct_shorter_justification() -> None:
    issues = validate_change_intent_field_separation(
        {
            "change_description": FUNCTIONAL_DESCRIPTION,
            "justification": DISTINCT_JUSTIFICATION,
        }
    )

    assert issues == []
    assert len(DISTINCT_JUSTIFICATION.split()) < len(FUNCTIONAL_DESCRIPTION.split())
    assert "necessary" in DISTINCT_JUSTIFICATION
    assert "reduces the risk" in DISTINCT_JUSTIFICATION


def test_final_payload_repairs_fields_and_preserves_eight_field_contract() -> None:
    change_description = (
        FUNCTIONAL_DESCRIPTION
        + " Build number 12345 from the main branch is deployed through ASAC-Release pipeline."
    )
    justification = (
        DISTINCT_JUSTIFICATION
        + " The release package was generated by pipeline from source commit abc123."
    )

    output = validate_and_assemble_outputs(
        build_id=101,
        llm_outputs=_full_llm_output(change_description, justification),
        evidence_bundle=_evidence_bundle(),
    )

    payload = output.service_now_payload.model_dump()
    assert tuple(payload) == SERVICE_NOW_FIELD_NAMES
    assert payload["change_description"] == FUNCTIONAL_DESCRIPTION
    assert payload["justification"] == DISTINCT_JUSTIFICATION
    assert len(payload["justification"].split()) < len(payload["change_description"].split())
    bucket_1_result = next(
        item for item in output.bucket_validation_results if item.bucket_name == "bucket_1"
    )
    assert bucket_1_result.repaired is True
    issue_codes = {issue.code for issue in output.validation_issues}
    assert "CHANGE_DESCRIPTION_DELIVERY_DETAIL_LEAKAGE" in issue_codes
    assert "JUSTIFICATION_DELIVERY_DETAIL_LEAKAGE" in issue_codes
